### ISSUE TITLE
Unicode filenames breaks MM

### ISSUE THREAD

**Issue by schnuti** [joomla-projects/media-manager-improvement#462]
### Expected result
The file should appear in MM with "funny" characters as in J3.x
alt. skip files with unicoded names.

### Actual result
No files or folders at all are displayed after a short "progress". 

### System information (as much as possible)
XAMPP local test, Win10

**Comment by schnuti** [comment]
This is because json_encode($array) throws an error when strings in the array is non UTF-8 as with Windows.
Solution 1:  json_encode($array, JSON_PARTIAL_OUTPUT_ON_ERROR) skips the non UTF-8 strings.
Solution 2: require PHP 7.1 for Joomla. That version handles the Windows filesystem.

**Comment by laoneo** [comment]
#463 should fix this issue.

**Comment by laoneo** [comment]
Issue can be closed as the pr got merged. Thanks for reporting.

**Comment by schnuti** [comment]
@laoneo 
Did you really test with a Windows system and PHP version < 7.1 ? With a PHP version > 7.0 or Linux the issue is solved. I still havn't seen anything about that Joomla 4 will raise the requirement to PHP > version 7.0. 
As I store utf8 filenames in the DB of my local system, I require PHP > 7.0. i.e. I'm not able to make a quick test. Better for Joomla is to raise the requirement.

**Comment by schnuti** [comment]
Well, I remembered, I still have an older XAMPP instance with PHP 7.0.4. After downloading the code from here I made a quick test. As I presumed - the problem remains. You have my two alternative solutions above. Image 1: fresh installation, Image 2: Übergrößen-länge.jpg added. = broken view. You can reopen the issue.

![original](https://user-images.githubusercontent.com/956537/34826103-89125b08-f6d5-11e7-8709-b4d204b7c284.jpg)

![unicodefile](https://user-images.githubusercontent.com/956537/34826116-9ae0a79a-f6d5-11e7-9bd4-e5b59a2b6315.jpg)

**Comment by laoneo** [comment]
It works on Linux, hope somebody else can help here out.

**Comment by kasvith** [comment]
I am using XAMMP with PHP 7, Windows 10 x64

I copied a file with unicode characters to the images directory and here is the result
![image](https://user-images.githubusercontent.com/13379595/34863567-1e49b53e-f796-11e7-920a-7ad32ba42eae.png)

In NMM

![image](https://user-images.githubusercontent.com/13379595/34863574-2b03b5f4-f796-11e7-8004-169f8eee68bd.png)

But after i tried to rename it to **Übergrößen länge nmm** the result is follows

![image](https://user-images.githubusercontent.com/13379595/34863606-57a7f822-f796-11e7-9046-7795c87789f4.png)

**Comment by laoneo** [comment]
That's a correct behavior as it strips out illegal characters when editing in MM. @schnuti do you use the latest code from the dev branch?

**Comment by kasvith** [comment]
If we want to keep the file name with UTF
Its needed to have  this extension installed in PHP according to this article

http://blog.garr.co.uk/php/2015/09/22/php-windows-and-utf-8-filenames.html

**Comment by laoneo** [comment]
The UTF issue is handled in core https://github.com/joomla/joomla-cms/pull/16878. Here we need to care only about when somebody uploaded a file with UTF characters trough FTP.

**Comment by schnuti** [comment]
Again -> from my post above

>This is because json_encode($array) throws an error when strings in the array is non UTF-8 as with Windows.
Solution 1: json_encode($array, JSON_PARTIAL_OUTPUT_ON_ERROR) skips the non UTF-8 strings.
>Solution 2: require PHP 7.1 for Joomla. That version handles the Windows filesystem.

To test you need a Windows system with **PHP 7.0x i.e. < 7.1**

If the PHP version requirement for Joomla 4 is raised to >= 7.1 this issue can be closed!
If it remains at PHP version 7.0 the json_encode statement has to be edited to include the above constant. In that case you will not see the  Übergrößen-länge.jpg on systems with PHP 7.0 but will appear on systems with PHP 7.1
I do hope that we do not need Solution 1! If you want to implement it anyway (it makes no harm) it's better you write the PR so I can be a tester on my Windows system.  

Clear enough?

@laoneo  My new test yesterday (Jan 11) was made with a download the same day.
I have to include the new Joomla instance with the IDE, if you want me to search for the line to edit. I knew the line as I started this issue.

**Comment by laoneo** [comment]
@schnuti I will discuss that issue in the PLT about a possible version increase to 7.1 for J4 as 7.0 will be EOL by December 2018 anyway.

**Comment by schnuti** [comment]
@laoneo 
My view is clear. The "vendor" versions required should be the latest "stable" versions at the time Joomla 4 goes live. I find Joomla 3 feels old because of the hard bindings to old versions of Php, JQuery, Bootstrap ... and the development cycles are getting even shorter.

For PHP
> Each release branch of PHP is fully supported for two years from its **initial stable release**.

**Comment by schnuti** [comment]
@laoneo 
To make sure that what I said is still true, I installed the same J40 MM code on a system with PHP 7.1.10.
As you can see the unicoded filename appears as expected. I didn't though find the line/lines to modify for PHP 7.0 after a quick search. I guess the code has bin modyfied a lot since last time I made a search.
![unicode-file](https://user-images.githubusercontent.com/956537/34904262-ae27f6f0-f842-11e7-935d-b056cbc95967.jpg)

**Comment by laoneo** [comment]
At the moment we stick with PHP 7.0 as min requirement. We can have a look on the issue again at a later point when we are in beta or rc phase when the PHP 7 version is fixed.

**Comment by schnuti** [comment]
OK! We just keep this issue open then.
